development:
  adapter: jdbcmysql
  encoding: utf8
  reconnect: false
  database: jruby_sample_app_development
  pool: 5
  username: root
  password:

test:
  adapter: jdbcmysql
  encoding: utf8
  reconnect: false
  database: jruby_sample_app_test
  pool: 5
  username: root
  password:

production:
  adapter: jdbcmysql
  encoding: utf8
  reconnect: false
  database: jruby_sample_app_production
  pool: 5
  username: root
  password:

